/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BlindHireInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bids"
      | "cancelJob"
      | "completeJob"
      | "confidentialProtocolId"
      | "getJob"
      | "getJobBidders"
      | "jobBidders"
      | "jobCount"
      | "jobs"
      | "postJob"
      | "selectWinner"
      | "submitBid"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BidSubmitted"
      | "JobCancelled"
      | "JobPosted"
      | "PaymentReleased"
      | "WinnerSelected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bids",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobBidders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "jobBidders",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "jobCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "jobs", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "postJob",
    values: [string, string, string, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "selectWinner",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBid",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "bids", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getJobBidders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobBidders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "selectWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitBid", data: BytesLike): Result;
}

export namespace BidSubmittedEvent {
  export type InputTuple = [jobId: BigNumberish, freelancer: AddressLike];
  export type OutputTuple = [jobId: bigint, freelancer: string];
  export interface OutputObject {
    jobId: bigint;
    freelancer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCancelledEvent {
  export type InputTuple = [jobId: BigNumberish];
  export type OutputTuple = [jobId: bigint];
  export interface OutputObject {
    jobId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobPostedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    client: AddressLike,
    title: string,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    client: string,
    title: string,
    deadline: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    client: string;
    title: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReleasedEvent {
  export type InputTuple = [jobId: BigNumberish, winner: AddressLike];
  export type OutputTuple = [jobId: bigint, winner: string];
  export interface OutputObject {
    jobId: bigint;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerSelectedEvent {
  export type InputTuple = [jobId: BigNumberish, winner: AddressLike];
  export type OutputTuple = [jobId: bigint, winner: string];
  export interface OutputObject {
    jobId: bigint;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlindHire extends BaseContract {
  connect(runner?: ContractRunner | null): BlindHire;
  waitForDeployment(): Promise<this>;

  interface: BlindHireInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bids: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, string, boolean] & {
        freelancer: string;
        encryptedAmount: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  cancelJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  completeJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getJob: TypedContractMethod<
    [jobId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        client: string;
        title: string;
        description: string;
        skillsRequired: string;
        deadline: bigint;
        status: bigint;
        winner: string;
        bidCount: bigint;
      }
    ],
    "view"
  >;

  getJobBidders: TypedContractMethod<[jobId: BigNumberish], [string[]], "view">;

  jobBidders: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  jobCount: TypedContractMethod<[], [bigint], "view">;

  jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        client: string;
        title: string;
        description: string;
        skillsRequired: string;
        deadline: bigint;
        encryptedBudget: string;
        status: bigint;
        winner: string;
        bidCount: bigint;
      }
    ],
    "view"
  >;

  postJob: TypedContractMethod<
    [
      title: string,
      description: string,
      skillsRequired: string,
      deadline: BigNumberish,
      encryptedBudget: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  selectWinner: TypedContractMethod<
    [jobId: BigNumberish, freelancer: AddressLike],
    [void],
    "nonpayable"
  >;

  submitBid: TypedContractMethod<
    [jobId: BigNumberish, encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bids"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, string, boolean] & {
        freelancer: string;
        encryptedAmount: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        client: string;
        title: string;
        description: string;
        skillsRequired: string;
        deadline: bigint;
        status: bigint;
        winner: string;
        bidCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJobBidders"
  ): TypedContractMethod<[jobId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "jobBidders"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        client: string;
        title: string;
        description: string;
        skillsRequired: string;
        deadline: bigint;
        encryptedBudget: string;
        status: bigint;
        winner: string;
        bidCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "postJob"
  ): TypedContractMethod<
    [
      title: string,
      description: string,
      skillsRequired: string,
      deadline: BigNumberish,
      encryptedBudget: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "selectWinner"
  ): TypedContractMethod<
    [jobId: BigNumberish, freelancer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitBid"
  ): TypedContractMethod<
    [jobId: BigNumberish, encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BidSubmitted"
  ): TypedContractEvent<
    BidSubmittedEvent.InputTuple,
    BidSubmittedEvent.OutputTuple,
    BidSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "JobCancelled"
  ): TypedContractEvent<
    JobCancelledEvent.InputTuple,
    JobCancelledEvent.OutputTuple,
    JobCancelledEvent.OutputObject
  >;
  getEvent(
    key: "JobPosted"
  ): TypedContractEvent<
    JobPostedEvent.InputTuple,
    JobPostedEvent.OutputTuple,
    JobPostedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReleased"
  ): TypedContractEvent<
    PaymentReleasedEvent.InputTuple,
    PaymentReleasedEvent.OutputTuple,
    PaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerSelected"
  ): TypedContractEvent<
    WinnerSelectedEvent.InputTuple,
    WinnerSelectedEvent.OutputTuple,
    WinnerSelectedEvent.OutputObject
  >;

  filters: {
    "BidSubmitted(uint256,address)": TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;
    BidSubmitted: TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;

    "JobCancelled(uint256)": TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;
    JobCancelled: TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;

    "JobPosted(uint256,address,string,uint256)": TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;
    JobPosted: TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;

    "PaymentReleased(uint256,address)": TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
    PaymentReleased: TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;

    "WinnerSelected(uint256,address)": TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
    WinnerSelected: TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
  };
}
